# Generated by Django 3.2.6 on 2022-06-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('preco', models.CharField(max_length=30)),
                ('imagem', models.ImageField(blank=True, upload_to='produtos/')),
                ('descriao', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
