# Generated by Django 3.2.6 on 2022-06-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20220615_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='descricao',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='horario',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/%Y/%m/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor'),
        ),
    ]
