# Generated by Django 3.2.6 on 2022-06-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20220616_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/'),
        ),
    ]
